stages:
- stage: Build
  jobs:
  - job: BuildTests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: mvn clean install
      displayName: 'Build and Install Tests'
    - publish: $(System.DefaultWorkingDirectory)/target/*.jar

- stage: Test
  dependsOn: Build
  jobs:
  - job: RunTests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: $(Build.ArtifactStagingDirectory)
    - script: mvn test
      displayName: 'Run Regression Tests'
    - publish: $(System.DefaultWorkingDirectory)/target/surefire-reports/*.xml
